// Code generated by MockGen. DO NOT EDIT.
// Source: intrface/order-repo.go

// Package mock_intrface is a generated GoMock package.
package mock_intrface

import (
	model "order-and-pay/model"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockOrderRepo is a mock of OrderRepo interface.
type MockOrderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepoMockRecorder
}

// MockOrderRepoMockRecorder is the mock recorder for MockOrderRepo.
type MockOrderRepoMockRecorder struct {
	mock *MockOrderRepo
}

// NewMockOrderRepo creates a new mock instance.
func NewMockOrderRepo(ctrl *gomock.Controller) *MockOrderRepo {
	mock := &MockOrderRepo{ctrl: ctrl}
	mock.recorder = &MockOrderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepo) EXPECT() *MockOrderRepoMockRecorder {
	return m.recorder
}

// AddPayment mocks base method.
func (m *MockOrderRepo) AddPayment(p *model.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPayment", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPayment indicates an expected call of AddPayment.
func (mr *MockOrderRepoMockRecorder) AddPayment(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPayment", reflect.TypeOf((*MockOrderRepo)(nil).AddPayment), p)
}

// AddProduct mocks base method.
func (m *MockOrderRepo) AddProduct(p *model.ProductInOrder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProduct", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockOrderRepoMockRecorder) AddProduct(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockOrderRepo)(nil).AddProduct), p)
}

// Begin mocks base method.
func (m *MockOrderRepo) Begin() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin")
	ret0, _ := ret[0].(error)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MockOrderRepoMockRecorder) Begin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockOrderRepo)(nil).Begin))
}

// Commit mocks base method.
func (m *MockOrderRepo) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockOrderRepoMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockOrderRepo)(nil).Commit))
}

// Create mocks base method.
func (m *MockOrderRepo) Create() (string, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockOrderRepoMockRecorder) Create() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderRepo)(nil).Create))
}

// DeleteProduct mocks base method.
func (m *MockOrderRepo) DeleteProduct(p *model.ProductInOrder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockOrderRepoMockRecorder) DeleteProduct(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockOrderRepo)(nil).DeleteProduct), p)
}

// GetAll mocks base method.
func (m *MockOrderRepo) GetAll(from, to time.Time) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", from, to)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockOrderRepoMockRecorder) GetAll(from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockOrderRepo)(nil).GetAll), from, to)
}

// GetById mocks base method.
func (m *MockOrderRepo) GetById(orderId string) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", orderId)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockOrderRepoMockRecorder) GetById(orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockOrderRepo)(nil).GetById), orderId)
}

// GetOrderStatus mocks base method.
func (m *MockOrderRepo) GetOrderStatus(orderId string) (uint8, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderStatus", orderId)
	ret0, _ := ret[0].(uint8)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderStatus indicates an expected call of GetOrderStatus.
func (mr *MockOrderRepoMockRecorder) GetOrderStatus(orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderStatus", reflect.TypeOf((*MockOrderRepo)(nil).GetOrderStatus), orderId)
}

// GetPaymentsByOrderId mocks base method.
func (m *MockOrderRepo) GetPaymentsByOrderId(orderId string) ([]model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentsByOrderId", orderId)
	ret0, _ := ret[0].([]model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentsByOrderId indicates an expected call of GetPaymentsByOrderId.
func (mr *MockOrderRepoMockRecorder) GetPaymentsByOrderId(orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentsByOrderId", reflect.TypeOf((*MockOrderRepo)(nil).GetPaymentsByOrderId), orderId)
}

// GetPaymentsSumByOrderId mocks base method.
func (m *MockOrderRepo) GetPaymentsSumByOrderId(orderId string) (float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentsSumByOrderId", orderId)
	ret0, _ := ret[0].(float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentsSumByOrderId indicates an expected call of GetPaymentsSumByOrderId.
func (mr *MockOrderRepoMockRecorder) GetPaymentsSumByOrderId(orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentsSumByOrderId", reflect.TypeOf((*MockOrderRepo)(nil).GetPaymentsSumByOrderId), orderId)
}

// GetProductId mocks base method.
func (m *MockOrderRepo) GetProductId(p *model.ProductInOrder) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductId", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductId indicates an expected call of GetProductId.
func (mr *MockOrderRepoMockRecorder) GetProductId(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductId", reflect.TypeOf((*MockOrderRepo)(nil).GetProductId), p)
}

// GetProductsByOrderId mocks base method.
func (m *MockOrderRepo) GetProductsByOrderId(orderId string) ([]model.ProductInOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsByOrderId", orderId)
	ret0, _ := ret[0].([]model.ProductInOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsByOrderId indicates an expected call of GetProductsByOrderId.
func (mr *MockOrderRepoMockRecorder) GetProductsByOrderId(orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsByOrderId", reflect.TypeOf((*MockOrderRepo)(nil).GetProductsByOrderId), orderId)
}

// GetProductsPriceSumByOrderId mocks base method.
func (m *MockOrderRepo) GetProductsPriceSumByOrderId(orderId string) (float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsPriceSumByOrderId", orderId)
	ret0, _ := ret[0].(float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsPriceSumByOrderId indicates an expected call of GetProductsPriceSumByOrderId.
func (mr *MockOrderRepoMockRecorder) GetProductsPriceSumByOrderId(orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsPriceSumByOrderId", reflect.TypeOf((*MockOrderRepo)(nil).GetProductsPriceSumByOrderId), orderId)
}

// Rollback mocks base method.
func (m *MockOrderRepo) Rollback() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Rollback")
}

// Rollback indicates an expected call of Rollback.
func (mr *MockOrderRepoMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockOrderRepo)(nil).Rollback))
}

// UpdateOrderStatusToComplete mocks base method.
func (m *MockOrderRepo) UpdateOrderStatusToComplete(orderId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatusToComplete", orderId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatusToComplete indicates an expected call of UpdateOrderStatusToComplete.
func (mr *MockOrderRepoMockRecorder) UpdateOrderStatusToComplete(orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatusToComplete", reflect.TypeOf((*MockOrderRepo)(nil).UpdateOrderStatusToComplete), orderId)
}

// UpdateProductNumById mocks base method.
func (m *MockOrderRepo) UpdateProductNumById(num, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductNumById", num, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProductNumById indicates an expected call of UpdateProductNumById.
func (mr *MockOrderRepoMockRecorder) UpdateProductNumById(num, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductNumById", reflect.TypeOf((*MockOrderRepo)(nil).UpdateProductNumById), num, id)
}
